import { PeriodKind, periodKind } from '../period.types';
import { StatisticCategories } from './category.types';
import {
  CategoryDataShape,
  categoryDataShape,
  CategoryRendererKey,
  categoryRendererKey,
} from './data-shape.types';

export const statisticCategoryDataShape = {
  totalParticipants: categoryDataShape.values,
  participantsGrowthRate: categoryDataShape.series,
  participationRecordYears: categoryDataShape.values,
  topNames: categoryDataShape.ranks,
  namesDiversity: categoryDataShape.values,
  nameTrends: categoryDataShape.series,
  newNames: categoryDataShape.ranks,
  disappearedNames: categoryDataShape.ranks,
  perennialNames: categoryDataShape.ranks,
  nameComebacks: categoryDataShape.ranks,
  averageNameLength: categoryDataShape.series,
  nameInitialDistribution: categoryDataShape.ranks,
  nameConcentration: categoryDataShape.values,
  singleYearNames: categoryDataShape.ranks,
  rareNames: categoryDataShape.ranks,
  longestNames: categoryDataShape.ranks,
  nameSchoolCorrelation: categoryDataShape.ranks,
  topSurnames: categoryDataShape.ranks,
  surnamesDiversity: categoryDataShape.values,
  surnameTrends: categoryDataShape.series,
  newSurnames: categoryDataShape.ranks,
  disappearedSurnames: categoryDataShape.ranks,
  perennialSurnames: categoryDataShape.ranks,
  surnameComebacks: categoryDataShape.ranks,
  averageSurnameLength: categoryDataShape.series,
  surnameInitialDistribution: categoryDataShape.ranks,
  surnameConcentration: categoryDataShape.values,
  singleYearSurnames: categoryDataShape.ranks,
  rareSurnames: categoryDataShape.ranks,
  longestSurnames: categoryDataShape.ranks,
  surnameSchoolCorrelation: categoryDataShape.ranks,
  nameSurnameDynasties: categoryDataShape.ranks,
  topSchools: categoryDataShape.ranks,
  newSchools: categoryDataShape.ranks,
  disappearedSchools: categoryDataShape.ranks,
  schoolLongevity: categoryDataShape.ranks,
  schoolGrowthRate: categoryDataShape.series,
  averageSchoolSize: categoryDataShape.series,
  schoolSizeDistribution: categoryDataShape.values,
  schoolNameDiversity: categoryDataShape.ranks,
  schoolSurnameDiversity: categoryDataShape.ranks,
  commonNameBySchool: categoryDataShape.ranks,
  schoolsEvolution: categoryDataShape.series,
  mostConstantSchools: categoryDataShape.ranks,
  newVsVeteranSchoolRatio: categoryDataShape.series,
  schoolsParticipantsCorrelation: categoryDataShape.series,
} as const satisfies Record<StatisticCategories, CategoryDataShape>;

export const statisticCategoryRendererKey = {
  totalParticipants: categoryRendererKey.metricCard,
  participantsGrowthRate: categoryRendererKey.lineChart,
  participationRecordYears: categoryRendererKey.metricCard,
  topNames: categoryRendererKey.horizontalRanking,
  namesDiversity: categoryRendererKey.metricCard,
  nameTrends: categoryRendererKey.lineChart,
  newNames: categoryRendererKey.horizontalRanking,
  disappearedNames: categoryRendererKey.horizontalRanking,
  perennialNames: categoryRendererKey.horizontalRanking,
  nameComebacks: categoryRendererKey.horizontalRanking,
  averageNameLength: categoryRendererKey.lineChart,
  nameInitialDistribution: categoryRendererKey.horizontalRanking,
  nameConcentration: categoryRendererKey.metricCard,
  singleYearNames: categoryRendererKey.horizontalRanking,
  rareNames: categoryRendererKey.horizontalRanking,
  longestNames: categoryRendererKey.horizontalRanking,
  nameSchoolCorrelation: categoryRendererKey.horizontalRanking,
  topSurnames: categoryRendererKey.horizontalRanking,
  surnamesDiversity: categoryRendererKey.metricCard,
  surnameTrends: categoryRendererKey.lineChart,
  newSurnames: categoryRendererKey.horizontalRanking,
  disappearedSurnames: categoryRendererKey.horizontalRanking,
  perennialSurnames: categoryRendererKey.horizontalRanking,
  surnameComebacks: categoryRendererKey.horizontalRanking,
  averageSurnameLength: categoryRendererKey.lineChart,
  surnameInitialDistribution: categoryRendererKey.horizontalRanking,
  surnameConcentration: categoryRendererKey.metricCard,
  singleYearSurnames: categoryRendererKey.horizontalRanking,
  rareSurnames: categoryRendererKey.horizontalRanking,
  longestSurnames: categoryRendererKey.horizontalRanking,
  surnameSchoolCorrelation: categoryRendererKey.horizontalRanking,
  nameSurnameDynasties: categoryRendererKey.horizontalRanking,
  topSchools: categoryRendererKey.horizontalRanking,
  newSchools: categoryRendererKey.horizontalRanking,
  disappearedSchools: categoryRendererKey.horizontalRanking,
  schoolLongevity: categoryRendererKey.horizontalRanking,
  schoolGrowthRate: categoryRendererKey.lineChart,
  averageSchoolSize: categoryRendererKey.lineChart,
  schoolSizeDistribution: categoryRendererKey.distributionChart,
  schoolNameDiversity: categoryRendererKey.horizontalRanking,
  schoolSurnameDiversity: categoryRendererKey.horizontalRanking,
  commonNameBySchool: categoryRendererKey.dataTable,
  schoolsEvolution: categoryRendererKey.lineChart,
  mostConstantSchools: categoryRendererKey.horizontalRanking,
  newVsVeteranSchoolRatio: categoryRendererKey.lineChart,
  schoolsParticipantsCorrelation: categoryRendererKey.scatterPlot,
} as const satisfies Record<StatisticCategories, CategoryRendererKey>;

export interface StatisticCategoryPeriodKindMap extends Readonly<
  Record<StatisticCategories, readonly PeriodKind[]>
> {}

export const statisticCategoryPeriodKind = {
  totalParticipants: [periodKind.year, periodKind.global],
  participantsGrowthRate: [periodKind.year, periodKind.global],
  participationRecordYears: [periodKind.global],
  topNames: [periodKind.year, periodKind.global],
  namesDiversity: [periodKind.year, periodKind.global],
  nameTrends: [periodKind.global],
  newNames: [periodKind.year],
  disappearedNames: [periodKind.year],
  perennialNames: [periodKind.global],
  nameComebacks: [periodKind.year, periodKind.global],
  averageNameLength: [periodKind.year],
  nameInitialDistribution: [periodKind.year, periodKind.global],
  nameConcentration: [periodKind.year, periodKind.global],
  singleYearNames: [periodKind.global],
  rareNames: [periodKind.global],
  longestNames: [periodKind.global],
  nameSchoolCorrelation: [periodKind.global],
  topSurnames: [periodKind.year, periodKind.global],
  surnamesDiversity: [periodKind.year, periodKind.global],
  surnameTrends: [periodKind.global],
  newSurnames: [periodKind.year],
  disappearedSurnames: [periodKind.year],
  perennialSurnames: [periodKind.global],
  surnameComebacks: [periodKind.year, periodKind.global],
  averageSurnameLength: [periodKind.year],
  surnameInitialDistribution: [periodKind.year, periodKind.global],
  surnameConcentration: [periodKind.year, periodKind.global],
  singleYearSurnames: [periodKind.global],
  rareSurnames: [periodKind.global],
  longestSurnames: [periodKind.global],
  surnameSchoolCorrelation: [periodKind.global],
  nameSurnameDynasties: [periodKind.global],
  topSchools: [periodKind.year, periodKind.global],
  newSchools: [periodKind.year],
  disappearedSchools: [periodKind.year],
  schoolLongevity: [periodKind.global],
  schoolGrowthRate: [periodKind.year],
  averageSchoolSize: [periodKind.year],
  schoolSizeDistribution: [periodKind.year, periodKind.global],
  schoolNameDiversity: [periodKind.year, periodKind.global],
  schoolSurnameDiversity: [periodKind.year, periodKind.global],
  commonNameBySchool: [periodKind.year, periodKind.global],
  schoolsEvolution: [periodKind.global],
  mostConstantSchools: [periodKind.global],
  newVsVeteranSchoolRatio: [periodKind.year],
  schoolsParticipantsCorrelation: [periodKind.global],
} as const satisfies StatisticCategoryPeriodKindMap;
